export type Product = {
  id: string;
  name: string;
  brand: string;
  health: "healthy" | "warning" | "critical";
  dependencyCount: number;
  adoptionPct: number;
  usageTrend30d: number[];
  description: string;
  tier: string;
  workspaceCount: number;
  release: string;
  uptime: number;
  errorRatePct: number;
};

export const products: Product[] = [
  {
    id: "sahayogi-one",
    name: "Sahayogi One",
    brand: "Sahayogi",
    health: "healthy",
    dependencyCount: 4,
    adoptionPct: 98,
    usageTrend30d: [88, 90, 91, 92, 93, 94, 95, 96, 97, 97, 98, 98],
    description: "Central workspace portal for user plan access, product subscriptions & expiry governance",
    tier: "Central Portal",
    workspaceCount: 2150,
    release: "v1.4.2",
    uptime: 99.99,
    errorRatePct: 0.01,
  },
  {
    id: "chat-sahayogi",
    name: "Chat with Sahayogi",
    brand: "Sahayogi",
    health: "warning",
    dependencyCount: 4,
    adoptionPct: 88,
    usageTrend30d: [72, 74, 75, 78, 80, 79, 83, 85, 84, 86, 88, 88],
    description: "Omnichannel conversational AI & WhatsApp Business Platform gateway",
    tier: "Business Application",
    workspaceCount: 1180,
    release: "v3.1.2",
    uptime: 97.4,
    errorRatePct: 0.18,
  },
  {
    id: "my-sahayogi",
    name: "My Sahayogi",
    brand: "Sahayogi",
    health: "healthy",
    dependencyCount: 4,
    adoptionPct: 84,
    usageTrend30d: [70, 72, 73, 75, 76, 77, 79, 81, 82, 83, 84, 84],
    description: "Personal employee self-service portal, workspace assistant & task hub",
    tier: "Productivity Portal",
    workspaceCount: 1340,
    release: "v2.1.0",
    uptime: 99.94,
    errorRatePct: 0.06,
  },
  {
    id: "tax-sahayogi",
    name: "Tax Sahayogi",
    brand: "Sahayogi",
    health: "healthy",
    dependencyCount: 4,
    adoptionPct: 76,
    usageTrend30d: [60, 62, 63, 65, 67, 68, 70, 72, 73, 74, 76, 76],
    description: "Automated GST, TDS, e-Invoicing, ITR filing & statutory financial compliance",
    tier: "Finance & Compliance",
    workspaceCount: 860,
    release: "v1.8.5",
    uptime: 99.88,
    errorRatePct: 0.06,
  },
  {
    id: "boss",
    name: "BoSS",
    brand: "Sahayogi",
    health: "healthy",
    dependencyCount: 4,
    adoptionPct: 79,
    usageTrend30d: [62, 64, 65, 67, 69, 70, 72, 74, 76, 77, 79, 79],
    description: "Business Operating System & enterprise back-office ERP suite",
    tier: "Enterprise ERP",
    workspaceCount: 980,
    release: "v4.0.2",
    uptime: 99.92,
    errorRatePct: 0.01,
  },
  {
    id: "office-sahayogi",
    name: "Office Sahayogi",
    brand: "Sahayogi",
    health: "healthy",
    dependencyCount: 4,
    adoptionPct: 71,
    usageTrend30d: [58, 60, 61, 63, 65, 66, 68, 69, 70, 70, 71, 71],
    description: "The AI-powered business doctor for Indian SMEs — operational consulting & system design",
    tier: "Consulting & Audit",
    workspaceCount: 740,
    release: "v2.3.0",
    uptime: 99.95,
    errorRatePct: 0.02,
  },
  {
    id: "investor-sahayogi",
    name: "Investor Sahayogi",
    brand: "Sahayogi",
    health: "healthy",
    dependencyCount: 4,
    adoptionPct: 82,
    usageTrend30d: [70, 72, 74, 76, 77, 78, 79, 80, 81, 81, 82, 82],
    description: "AMFI-registered financial planning for mutual funds, PMS, insurance, loans and wealth structuring",
    tier: "Wealth & Finance",
    workspaceCount: 940,
    release: "v2.1.0",
    uptime: 99.96,
    errorRatePct: 0.02,
  },
  {
    id: "sahayogi-cloud",
    name: "Sahayogi Cloud",
    brand: "Sahayogi",
    health: "healthy",
    dependencyCount: 4,
    adoptionPct: 94,
    usageTrend30d: [80, 82, 83, 85, 87, 88, 90, 91, 92, 93, 94, 94],
    description: "Core workspace orchestration & distributed cloud infrastructure",
    tier: "Core Platform",
    workspaceCount: 1420,
    release: "v2.8.4",
    uptime: 99.98,
    errorRatePct: 0.01,
  },
  {
    id: "studio-sahayogi",
    name: "Studio Sahayogi",
    brand: "Sahayogi",
    health: "healthy",
    dependencyCount: 3,
    adoptionPct: 72,
    usageTrend30d: [56, 58, 59, 61, 63, 64, 66, 68, 69, 70, 72, 72],
    description: "Drag-and-drop workflow builder, automation rules & bot studio",
    tier: "Workflow Engine",
    workspaceCount: 890,
    release: "v1.9.0",
    uptime: 99.95,
    errorRatePct: 0.07,
  },
];

export const productKpis = {
  live: products.length,
  averageAdoptionPct: 85,
  workspacesNearLimit: 8,
  totalWorkspaces: 2150,
  managedFeatures: 16,
  avgAdoptionRate: 85.6,
};
