// Sahayogi Setu V2 - Product Manager Mock Data Layer
// Canonical domain objects: Products, Features, Feature Flags, Rollouts, Usage Meters, Entitlements, Releases, Health, Incidents, Dependencies, Costs, Controls & Risks
// Total 9 Products: Sahayogi One, Chat with Sahayogi, My Sahayogi, Tax Sahayogi, BoSS, Office Sahayogi, Investor Sahayogi, Sahayogi Cloud, Studio Sahayogi

export const mockCurrentUser = {
  name: "Dhruv Singla",
  role: "Product Manager",
  workspace: "Sahayogi Production",
  tenant: "Tenant Zero (Internal)",
  avatarInitials: "DS",
  email: "dhruv.singla@sahayogi.internal",
  unreadNotifications: 3,
};

export const mockProducts = [
  {
    id: "sahayogi-one",
    name: "Sahayogi One",
    tagline: "Central workspace portal for user plan access, product subscriptions & expiry governance",
    status: "Healthy",
    tier: "Central Portal",
    workspaceCount: 2150,
    planCount: 4,
    usageMetric: "3.2M auth & plan checks/mo",
    adoptionRate: 98.5,
    health: {
      status: "Healthy",
      score: 99.99,
      apiStatus: "Operational",
      dbStatus: "Operational",
      aiStatus: "Operational",
      messagingStatus: "Operational",
    },
    release: "v1.4.2",
    currentVersion: "1.4.2",
    operationalCost: {
      total: 2140,
      currency: "USD",
      infra: 1200,
      aiProvider: 120,
      messaging: 320,
      storage: 500,
      variance: "+1.8%",
    },
    dependencies: [
      { name: "Auth & Identity (Sahayogi One ID)", type: "Core Service", state: "Healthy", impact: "Critical", incident: null },
      { name: "Subscription & Licensing Engine", type: "Billing Service", state: "Healthy", impact: "Critical", incident: null },
      { name: "PostgreSQL Primary User Directory", type: "Database", state: "Healthy", impact: "Critical", incident: null },
      { name: "Redis Distributed Session Store", type: "Caching", state: "Healthy", impact: "High", incident: null },
    ],
    incidents: [],
    controls: { active: 22, needsReview: 0 },
    risks: { open: 1, requiringAttention: 0 },
  },
  {
    id: "chat-sahayogi",
    name: "Chat with Sahayogi",
    tagline: "Omnichannel conversational AI & WhatsApp Business Platform gateway",
    status: "Degraded",
    tier: "Business Application",
    workspaceCount: 1180,
    planCount: 3,
    usageMetric: "4.8M messages/mo",
    adoptionRate: 88.6,
    health: {
      status: "Degraded",
      score: 97.4,
      apiStatus: "Operational",
      dbStatus: "Operational",
      aiStatus: "Degraded",
      messagingStatus: "Operational",
    },
    release: "v3.1.2",
    currentVersion: "3.1.2",
    operationalCost: {
      total: 5860,
      currency: "USD",
      infra: 1200,
      aiProvider: 2450,
      messaging: 1980,
      storage: 230,
      variance: "+12.8%",
    },
    dependencies: [
      { name: "Meta WhatsApp Cloud API", type: "Integration", state: "Healthy", impact: "Critical", incident: null },
      { name: "OpenAI Model Gateway", type: "AI Provider", state: "Degraded", impact: "High", incident: "INC-910" },
      { name: "Kafka Event Bus", type: "Messaging", state: "Healthy", impact: "High", incident: null },
      { name: "Elasticsearch Index", type: "Search", state: "Healthy", impact: "Medium", incident: null },
    ],
    incidents: [
      { id: "INC-910", title: "Upstream AI Model Gateway latency degradation (P99 > 1800ms)", severity: "Medium", status: "Investigating", time: "28 mins ago" }
    ],
    controls: { active: 18, needsReview: 1 },
    risks: { open: 4, requiringAttention: 1 },
  },
  {
    id: "my-sahayogi",
    name: "My Sahayogi",
    tagline: "Personal employee self-service portal, workspace assistant & task hub",
    status: "Healthy",
    tier: "Productivity Portal",
    workspaceCount: 1340,
    planCount: 3,
    usageMetric: "920K employee sessions/mo",
    adoptionRate: 84.1,
    health: {
      status: "Healthy",
      score: 99.94,
      apiStatus: "Operational",
      dbStatus: "Operational",
      aiStatus: "Operational",
      messagingStatus: "Operational",
    },
    release: "v2.1.0",
    currentVersion: "2.1.0",
    operationalCost: {
      total: 1650,
      currency: "USD",
      infra: 900,
      aiProvider: 380,
      messaging: 120,
      storage: 250,
      variance: "+2.4%",
    },
    dependencies: [
      { name: "Sahayogi One RBAC & Session Sync", type: "Core Service", state: "Healthy", impact: "Critical", incident: null },
      { name: "HRMS & Attendance Event Bridge", type: "Integration", state: "Healthy", impact: "High", incident: null },
      { name: "Mobile Push Notification Service", type: "Notification", state: "Healthy", impact: "Medium", incident: null },
      { name: "Task Scheduler & Reminder Engine", type: "Scheduler", state: "Healthy", impact: "Medium", incident: null },
    ],
    incidents: [],
    controls: { active: 15, needsReview: 0 },
    risks: { open: 1, requiringAttention: 0 },
  },
  {
    id: "tax-sahayogi",
    name: "Tax Sahayogi",
    tagline: "Automated GST, TDS, e-Invoicing, ITR filing & statutory financial compliance",
    status: "Healthy",
    tier: "Finance & Compliance",
    workspaceCount: 860,
    planCount: 3,
    usageMetric: "410K invoices reconciled/mo",
    adoptionRate: 76.8,
    health: {
      status: "Healthy",
      score: 99.88,
      apiStatus: "Operational",
      dbStatus: "Operational",
      aiStatus: "Operational",
      messagingStatus: "Operational",
    },
    release: "v1.8.5",
    currentVersion: "1.8.5",
    operationalCost: {
      total: 2420,
      currency: "USD",
      infra: 1100,
      aiProvider: 220,
      messaging: 100,
      storage: 1000,
      variance: "-0.8%",
    },
    dependencies: [
      { name: "Govt GST / NIC e-Invoice Gateway", type: "External Provider", state: "Degraded", impact: "High", incident: "INC-899" },
      { name: "Income Tax Department e-Filing API", type: "External Provider", state: "Healthy", impact: "High", incident: null },
      { name: "Cryptographic DSC Signing Vault", type: "Security Vault", state: "Healthy", impact: "Critical", incident: null },
      { name: "BoSS Financial Ledger Connector", type: "Internal Bridge", state: "Healthy", impact: "High", incident: null },
    ],
    incidents: [
      { id: "INC-899", title: "Govt GST portal sandbox endpoint maintenance", severity: "Low", status: "Monitoring", time: "4 hours ago" }
    ],
    controls: { active: 20, needsReview: 0 },
    risks: { open: 2, requiringAttention: 0 },
  },
  {
    id: "boss",
    name: "BoSS",
    tagline: "Business Operations & System Suite — HR, payroll, finance, inventory, CRM and compliance in one place",
    status: "Healthy",
    tier: "Enterprise ERP",
    workspaceCount: 980,
    planCount: 3,
    usageMetric: "1.8M ledger transactions/mo",
    adoptionRate: 79.3,
    health: {
      status: "Healthy",
      score: 99.92,
      apiStatus: "Operational",
      dbStatus: "Operational",
      aiStatus: "Operational",
      messagingStatus: "Operational",
    },
    release: "v4.0.2",
    currentVersion: "4.0.2",
    operationalCost: {
      total: 3120,
      currency: "USD",
      infra: 1800,
      aiProvider: 180,
      messaging: 340,
      storage: 800,
      variance: "+1.1%",
    },
    dependencies: [
      { name: "PostgreSQL Primary Financial Ledger", type: "Database", state: "Healthy", impact: "Critical", incident: null },
      { name: "Tally & BUSY Desktop Connector Agent", type: "External Client", state: "Healthy", impact: "High", incident: null },
      { name: "Open Banking & Razorpay Webhooks", type: "Fintech Gateway", state: "Healthy", impact: "Critical", incident: null },
      { name: "Audit Log & SOC2 Compliance Vault", type: "Compliance Vault", state: "Healthy", impact: "High", incident: null },
    ],
    incidents: [],
    controls: { active: 24, needsReview: 0 },
    risks: { open: 2, requiringAttention: 0 },
  },
  {
    id: "office-sahayogi",
    name: "Office Sahayogi",
    tagline: "The AI-powered business doctor for Indian SMEs — operational consulting & system design",
    status: "Healthy",
    tier: "Consulting & Audit",
    workspaceCount: 740,
    planCount: 2,
    usageMetric: "420K consultation & audit checks/mo",
    adoptionRate: 71.5,
    health: {
      status: "Healthy",
      score: 99.95,
      apiStatus: "Operational",
      dbStatus: "Operational",
      aiStatus: "Operational",
      messagingStatus: "Operational",
    },
    release: "v2.3.0",
    currentVersion: "2.3.0",
    operationalCost: {
      total: 1850,
      currency: "USD",
      infra: 950,
      aiProvider: 420,
      messaging: 180,
      storage: 300,
      variance: "+0.8%",
    },
    dependencies: [
      { name: "SME Diagnostic Knowledge Graph", type: "Core AI Service", state: "Healthy", impact: "Critical", incident: null },
      { name: "Operational Workflow Engine", type: "Workflow Service", state: "Healthy", impact: "High", incident: null },
      { name: "PostgreSQL Consulting DB", type: "Database", state: "Healthy", impact: "High", incident: null },
      { name: "Vector Embeddings Store", type: "AI Store", state: "Healthy", impact: "Medium", incident: null },
    ],
    incidents: [],
    controls: { active: 18, needsReview: 0 },
    risks: { open: 1, requiringAttention: 0 },
  },
  {
    id: "investor-sahayogi",
    name: "Investor Sahayogi",
    tagline: "AMFI-registered financial planning for mutual funds, PMS, insurance, loans and wealth structuring",
    status: "Healthy",
    tier: "Wealth & Finance",
    workspaceCount: 940,
    planCount: 3,
    usageMetric: "680K portfolio valuations/mo",
    adoptionRate: 82.4,
    health: {
      status: "Healthy",
      score: 99.96,
      apiStatus: "Operational",
      dbStatus: "Operational",
      aiStatus: "Operational",
      messagingStatus: "Operational",
    },
    release: "v2.1.0",
    currentVersion: "2.1.0",
    operationalCost: {
      total: 2680,
      currency: "USD",
      infra: 1350,
      aiProvider: 320,
      messaging: 410,
      storage: 600,
      variance: "+1.4%",
    },
    dependencies: [
      { name: "AMFI Mutual Fund NAV Feed Gateway", type: "Fintech Gateway", state: "Healthy", impact: "Critical", incident: null },
      { name: "BSE StAR MF / NSE NMF Order Routing", type: "Exchange Gateway", state: "Healthy", impact: "Critical", incident: null },
      { name: "Portfolio Valuation Engine", type: "Core Engine", state: "Healthy", impact: "Critical", incident: null },
      { name: "CAMS & KFintech RTAs Reconciler", type: "Sync Service", state: "Healthy", impact: "High", incident: null },
    ],
    incidents: [],
    controls: { active: 22, needsReview: 0 },
    risks: { open: 1, requiringAttention: 0 },
  },
  {
    id: "sahayogi-cloud",
    name: "Sahayogi Cloud",
    tagline: "Core workspace orchestration & distributed cloud infrastructure",
    status: "Healthy",
    tier: "Core Platform",
    workspaceCount: 1420,
    planCount: 4,
    usageMetric: "8.4M compute units/mo",
    adoptionRate: 94.2,
    health: {
      status: "Healthy",
      score: 99.98,
      apiStatus: "Operational",
      dbStatus: "Operational",
      aiStatus: "Operational",
      messagingStatus: "Operational",
    },
    release: "v2.8.4",
    currentVersion: "2.8.4",
    operationalCost: {
      total: 3840,
      currency: "USD",
      infra: 2100,
      aiProvider: 420,
      messaging: 620,
      storage: 700,
      variance: "+3.2%",
    },
    dependencies: [
      { name: "Auth & Identity (Sahayogi One)", type: "Core Service", state: "Healthy", impact: "High", incident: null },
      { name: "PostgreSQL Primary Cluster", type: "Database", state: "Healthy", impact: "Critical", incident: null },
      { name: "Redis Cache Tier", type: "Caching", state: "Healthy", impact: "Medium", incident: null },
      { name: "AWS Cloud Infrastructure", type: "Cloud Provider", state: "Healthy", impact: "Critical", incident: null },
    ],
    incidents: [
      { id: "INC-842", title: "Intermittent Redis cache eviction spike", severity: "Low", status: "Resolved", time: "2 days ago" }
    ],
    controls: { active: 14, needsReview: 0 },
    risks: { open: 2, requiringAttention: 0 },
  },
  {
    id: "studio-sahayogi",
    name: "Studio Sahayogi",
    tagline: "Drag-and-drop workflow builder, automation rules & bot studio",
    status: "Healthy",
    tier: "Workflow Engine",
    workspaceCount: 890,
    planCount: 3,
    usageMetric: "1.2M workflow runs/mo",
    adoptionRate: 72.4,
    health: {
      status: "Healthy",
      score: 99.95,
      apiStatus: "Operational",
      dbStatus: "Operational",
      aiStatus: "Operational",
      messagingStatus: "Operational",
    },
    release: "v1.9.0",
    currentVersion: "1.9.0",
    operationalCost: {
      total: 1920,
      currency: "USD",
      infra: 1100,
      aiProvider: 320,
      messaging: 180,
      storage: 320,
      variance: "-1.4%",
    },
    dependencies: [
      { name: "Workflow Execution Engine", type: "Core Component", state: "Healthy", impact: "Critical", incident: null },
      { name: "Webhook Dispatcher Queue", type: "Queue Service", state: "Healthy", impact: "High", incident: null },
      { name: "Cron Scheduler", type: "Scheduler", state: "Healthy", impact: "High", incident: null },
    ],
    incidents: [],
    controls: { active: 12, needsReview: 0 },
    risks: { open: 1, requiringAttention: 0 },
  },
];

export const mockFeatures = [
  // Sahayogi One
  {
    id: "feat-subscription-hub",
    name: "Unified Subscription & License Hub",
    productId: "sahayogi-one",
    productName: "Sahayogi One",
    description: "Centralized space for users to manage active product access, view subscription tiers, plan entitlements, and track expiry dates",
    availability: ["Free", "Pro", "Business", "Enterprise"],
    adoptionRate: 98.2,
    activeWorkspaces: 2110,
    monthlyUsage: "3,200,000 checks",
    flagId: "flag-subscription-hub",
    rolloutPercentage: 100,
    status: "GA",
    telemetryGate: {
      errorRateThreshold: "< 0.05%",
      currentErrorRate: "0.01%",
      latencyThreshold: "< 150ms",
      currentLatency: "48ms",
      healthy: true,
    },
    whoHasAccess: [
      { plan: "Free", workspaces: 410, access: true },
      { plan: "Pro", workspaces: 720, access: true },
      { plan: "Business", workspaces: 680, access: true },
      { plan: "Enterprise", workspaces: 300, access: true },
    ],
  },
  {
    id: "feat-sso-rbac",
    name: "Central SSO & Multi-Tenant RBAC",
    productId: "sahayogi-one",
    productName: "Sahayogi One",
    description: "Single sign-on authentication and unified workspace permission matrix across all 8 Sahayogi products",
    availability: ["Pro", "Business", "Enterprise"],
    adoptionRate: 89.4,
    activeWorkspaces: 1680,
    monthlyUsage: "4,900,000 auth events",
    flagId: "flag-sso-rbac",
    rolloutPercentage: 100,
    status: "GA",
    telemetryGate: {
      errorRateThreshold: "< 0.05%",
      currentErrorRate: "0.008%",
      latencyThreshold: "< 100ms",
      currentLatency: "38ms",
      healthy: true,
    },
    whoHasAccess: [
      { plan: "Free", workspaces: 0, access: false },
      { plan: "Pro", workspaces: 700, access: true },
      { plan: "Business", workspaces: 680, access: true },
      { plan: "Enterprise", workspaces: 300, access: true },
    ],
  },

  // Chat with Sahayogi
  {
    id: "feat-ai-assistant-v2",
    name: "AI Assistant V2",
    productId: "chat-sahayogi",
    productName: "Chat with Sahayogi",
    description: "Next-gen contextual reasoning assistant with multi-turn memory and sentiment classification",
    availability: ["Pro", "Business", "Enterprise"],
    adoptionRate: 74.5,
    activeWorkspaces: 878,
    monthlyUsage: "1,420,000 tokens",
    flagId: "flag-ai-assistant-v2",
    rolloutPercentage: 65,
    status: "Active",
    telemetryGate: {
      errorRateThreshold: "< 0.5%",
      currentErrorRate: "0.18%",
      latencyThreshold: "< 600ms",
      currentLatency: "412ms",
      healthy: true,
    },
    whoHasAccess: [
      { plan: "Free", workspaces: 0, access: false },
      { plan: "Pro", workspaces: 340, access: true },
      { plan: "Business", workspaces: 410, access: true },
      { plan: "Enterprise", workspaces: 128, access: true },
    ],
  },
  {
    id: "feat-whatsapp-cloud-v19",
    name: "WhatsApp Cloud API v19",
    productId: "chat-sahayogi",
    productName: "Chat with Sahayogi",
    description: "Meta v19 Graph API compliance with interactive catalog buttons and direct UPI checkout",
    availability: ["Free", "Pro", "Business", "Enterprise"],
    adoptionRate: 92.4,
    activeWorkspaces: 1090,
    monthlyUsage: "840,000 msgs",
    flagId: "flag-waba-v19",
    rolloutPercentage: 100,
    status: "GA",
    telemetryGate: {
      errorRateThreshold: "< 0.2%",
      currentErrorRate: "0.04%",
      latencyThreshold: "< 350ms",
      currentLatency: "194ms",
      healthy: true,
    },
    whoHasAccess: [
      { plan: "Free", workspaces: 210, access: true },
      { plan: "Pro", workspaces: 390, access: true },
      { plan: "Business", workspaces: 370, access: true },
      { plan: "Enterprise", workspaces: 120, access: true },
    ],
  },

  // My Sahayogi
  {
    id: "feat-employee-self-service",
    name: "Employee Self-Service & Tasks",
    productId: "my-sahayogi",
    productName: "My Sahayogi",
    description: "Personal employee portal for geo-tagged attendance, automated leave requests, expense logging & team task queues",
    availability: ["Pro", "Business", "Enterprise"],
    adoptionRate: 84.1,
    activeWorkspaces: 1120,
    monthlyUsage: "780,000 actions",
    flagId: "flag-employee-portal",
    rolloutPercentage: 80,
    status: "Active",
    telemetryGate: {
      errorRateThreshold: "< 0.2%",
      currentErrorRate: "0.06%",
      latencyThreshold: "< 250ms",
      currentLatency: "128ms",
      healthy: true,
    },
    whoHasAccess: [
      { plan: "Free", workspaces: 0, access: false },
      { plan: "Pro", workspaces: 420, access: true },
      { plan: "Business", workspaces: 460, access: true },
      { plan: "Enterprise", workspaces: 240, access: true },
    ],
  },
  {
    id: "feat-workspace-assistant",
    name: "AI Workspace Assistant",
    productId: "my-sahayogi",
    productName: "My Sahayogi",
    description: "Personalized AI copilot summarizing pending items, drafting internal requests and syncing calendar tasks",
    availability: ["Business", "Enterprise"],
    adoptionRate: 67.5,
    activeWorkspaces: 710,
    monthlyUsage: "390,000 interactions",
    flagId: "flag-my-copilot",
    rolloutPercentage: 50,
    status: "Active",
    telemetryGate: {
      errorRateThreshold: "< 0.3%",
      currentErrorRate: "0.11%",
      latencyThreshold: "< 500ms",
      currentLatency: "310ms",
      healthy: true,
    },
    whoHasAccess: [
      { plan: "Free", workspaces: 0, access: false },
      { plan: "Pro", workspaces: 0, access: false },
      { plan: "Business", workspaces: 470, access: true },
      { plan: "Enterprise", workspaces: 240, access: true },
    ],
  },

  // Tax Sahayogi
  {
    id: "feat-gst-reconciliation",
    name: "Automated 2B GST Reconciliation",
    productId: "tax-sahayogi",
    productName: "Tax Sahayogi",
    description: "Real-time AI matching of purchase registers against GSTR-2B data with automated ITC mismatch reconciliation",
    availability: ["Pro", "Business", "Enterprise"],
    adoptionRate: 76.8,
    activeWorkspaces: 660,
    monthlyUsage: "320,000 reconciliations",
    flagId: "flag-gst-reconciliation",
    rolloutPercentage: 90,
    status: "Active",
    telemetryGate: {
      errorRateThreshold: "< 0.3%",
      currentErrorRate: "0.09%",
      latencyThreshold: "< 800ms",
      currentLatency: "410ms",
      healthy: true,
    },
    whoHasAccess: [
      { plan: "Free", workspaces: 0, access: false },
      { plan: "Pro", workspaces: 240, access: true },
      { plan: "Business", workspaces: 280, access: true },
      { plan: "Enterprise", workspaces: 140, access: true },
    ],
  },
  {
    id: "feat-e-invoice-irp",
    name: "Instant e-Invoice & e-Way Bill",
    productId: "tax-sahayogi",
    productName: "Tax Sahayogi",
    description: "Sub-second direct integration with Government IRP portal for signed IRN generation and instant QR code embedding",
    availability: ["Business", "Enterprise"],
    adoptionRate: 83.2,
    activeWorkspaces: 420,
    monthlyUsage: "180,000 e-invoices",
    flagId: "flag-e-invoice-irp",
    rolloutPercentage: 100,
    status: "GA",
    telemetryGate: {
      errorRateThreshold: "< 0.1%",
      currentErrorRate: "0.02%",
      latencyThreshold: "< 1200ms",
      currentLatency: "640ms",
      healthy: true,
    },
    whoHasAccess: [
      { plan: "Free", workspaces: 0, access: false },
      { plan: "Pro", workspaces: 0, access: false },
      { plan: "Business", workspaces: 280, access: true },
      { plan: "Enterprise", workspaces: 140, access: true },
    ],
  },

  // BoSS
  {
    id: "feat-double-entry-ledger",
    name: "Enterprise Double-Entry Ledger",
    productId: "boss",
    productName: "BoSS",
    description: "Real-time double-entry general ledger, automated trial balance, multi-branch chart of accounts, and financial statement rollups",
    availability: ["Pro", "Business", "Enterprise"],
    adoptionRate: 79.3,
    activeWorkspaces: 780,
    monthlyUsage: "1,800,000 transactions",
    flagId: "flag-boss-gl",
    rolloutPercentage: 100,
    status: "GA",
    telemetryGate: {
      errorRateThreshold: "< 0.05%",
      currentErrorRate: "0.01%",
      latencyThreshold: "< 300ms",
      currentLatency: "115ms",
      healthy: true,
    },
    whoHasAccess: [
      { plan: "Free", workspaces: 0, access: false },
      { plan: "Pro", workspaces: 290, access: true },
      { plan: "Business", workspaces: 340, access: true },
      { plan: "Enterprise", workspaces: 150, access: true },
    ],
  },
  {
    id: "feat-tally-direct",
    name: "Tally & BUSY Direct Cloud Sync",
    productId: "boss",
    productName: "BoSS",
    description: "Bi-directional real-time ledger & voucher synchronization with TallyPrime and BUSY without manual XML exports",
    availability: ["Pro", "Business", "Enterprise"],
    adoptionRate: 56.1,
    activeWorkspaces: 359,
    monthlyUsage: "48,000 syncs",
    flagId: "flag-tally-sync",
    rolloutPercentage: 50,
    status: "Paused",
    telemetryGate: {
      errorRateThreshold: "< 0.5%",
      currentErrorRate: "1.24%",
      latencyThreshold: "< 2000ms",
      currentLatency: "3400ms",
      healthy: false,
    },
    whoHasAccess: [
      { plan: "Free", workspaces: 0, access: false },
      { plan: "Pro", workspaces: 140, access: true },
      { plan: "Business", workspaces: 165, access: true },
      { plan: "Enterprise", workspaces: 54, access: true },
    ],
  },

  // Sahayogi AI
  {
    id: "feat-llm-router",
    name: "Cognitive Multi-Model LLM Router",
    productId: "sahayogi-ai",
    productName: "Sahayogi AI",
    description: "Dynamic latency and cost-optimized routing between OpenAI, Anthropic, and open-source models with prompt caching and token budgeting",
    availability: ["Pro", "Business", "Enterprise"],
    adoptionRate: 91.0,
    activeWorkspaces: 1140,
    monthlyUsage: "18,600,000 tokens",
    flagId: "flag-llm-router",
    rolloutPercentage: 75,
    status: "Active",
    telemetryGate: {
      errorRateThreshold: "< 0.3%",
      currentErrorRate: "0.08%",
      latencyThreshold: "< 700ms",
      currentLatency: "345ms",
      healthy: true,
    },
    whoHasAccess: [
      { plan: "Free", workspaces: 0, access: false },
      { plan: "Pro", workspaces: 410, access: true },
      { plan: "Business", workspaces: 480, access: true },
      { plan: "Enterprise", workspaces: 250, access: true },
    ],
  },
  {
    id: "feat-rag-vector-search",
    name: "Enterprise RAG Hybrid Vector Search",
    productId: "sahayogi-ai",
    productName: "Sahayogi AI",
    description: "Sub-50ms hybrid dense/sparse vector retrieval with automated tenant partitioning and zero data leakage guarantees",
    availability: ["Business", "Enterprise"],
    adoptionRate: 72.8,
    activeWorkspaces: 630,
    monthlyUsage: "4,200,000 queries",
    flagId: "flag-rag-vector",
    rolloutPercentage: 100,
    status: "GA",
    telemetryGate: {
      errorRateThreshold: "< 0.1%",
      currentErrorRate: "0.02%",
      latencyThreshold: "< 150ms",
      currentLatency: "58ms",
      healthy: true,
    },
    whoHasAccess: [
      { plan: "Free", workspaces: 0, access: false },
      { plan: "Pro", workspaces: 0, access: false },
      { plan: "Business", workspaces: 430, access: true },
      { plan: "Enterprise", workspaces: 200, access: true },
    ],
  },

  // Sahayogi Cloud
  {
    id: "feat-bulk-export",
    name: "Encrypted Bulk Data Export",
    productId: "sahayogi-cloud",
    productName: "Sahayogi Cloud",
    description: "Asynchronous zero-knowledge encrypted multi-tenant data exports with automated checksums",
    availability: ["Business", "Enterprise"],
    adoptionRate: 48.2,
    activeWorkspaces: 256,
    monthlyUsage: "12,400 exports",
    flagId: "flag-bulk-export",
    rolloutPercentage: 100,
    status: "GA",
    telemetryGate: {
      errorRateThreshold: "< 0.1%",
      currentErrorRate: "0.01%",
      latencyThreshold: "< 5000ms",
      currentLatency: "2100ms",
      healthy: true,
    },
    whoHasAccess: [
      { plan: "Free", workspaces: 0, access: false },
      { plan: "Pro", workspaces: 0, access: false },
      { plan: "Business", workspaces: 172, access: true },
      { plan: "Enterprise", workspaces: 84, access: true },
    ],
  },
  {
    id: "feat-advanced-reporting",
    name: "Executive BI & Advanced Reports",
    productId: "sahayogi-cloud",
    productName: "Sahayogi Cloud",
    description: "Custom cohorts, lifecycle stage analytics, and exportable executive PDF/CSV dashboards",
    availability: ["Pro", "Business", "Enterprise"],
    adoptionRate: 81.0,
    activeWorkspaces: 710,
    monthlyUsage: "42,000 reports",
    flagId: "flag-adv-reports",
    rolloutPercentage: 100,
    status: "GA",
    telemetryGate: {
      errorRateThreshold: "< 0.2%",
      currentErrorRate: "0.02%",
      latencyThreshold: "< 800ms",
      currentLatency: "310ms",
      healthy: true,
    },
    whoHasAccess: [
      { plan: "Free", workspaces: 0, access: false },
      { plan: "Pro", workspaces: 280, access: true },
      { plan: "Business", workspaces: 330, access: true },
      { plan: "Enterprise", workspaces: 100, access: true },
    ],
  },
  {
    id: "feat-priority-sla",
    name: "Sub-100ms Priority SLA",
    productId: "sahayogi-cloud",
    productName: "Sahayogi Cloud",
    description: "Dedicated routing lane and warm memory tier ensuring sub-100ms P99 compute responsiveness",
    availability: ["Enterprise"],
    adoptionRate: 29.3,
    activeWorkspaces: 38,
    monthlyUsage: "99.99% compliant",
    flagId: "flag-priority-sla",
    rolloutPercentage: 100,
    status: "GA",
    telemetryGate: {
      errorRateThreshold: "< 0.05%",
      currentErrorRate: "0.005%",
      latencyThreshold: "< 100ms",
      currentLatency: "64ms",
      healthy: true,
    },
    whoHasAccess: [
      { plan: "Free", workspaces: 0, access: false },
      { plan: "Pro", workspaces: 0, access: false },
      { plan: "Business", workspaces: 0, access: false },
      { plan: "Enterprise", workspaces: 38, access: true },
    ],
  },

  // Office Sahayogi
  {
    id: "feat-sme-diagnostic",
    name: "SME Operational Health Diagnostic",
    productId: "office-sahayogi",
    productName: "Office Sahayogi",
    description: "Automated operational health audit, bottleneck detection & system architecture blueprint for SMEs",
    availability: ["Pro", "Business", "Enterprise"],
    adoptionRate: 71.5,
    activeWorkspaces: 530,
    monthlyUsage: "420,000 audits",
    flagId: "flag-office-diagnostic",
    rolloutPercentage: 100,
    status: "GA",
    telemetryGate: {
      errorRateThreshold: "< 0.05%",
      currentErrorRate: "0.02%",
      latencyThreshold: "< 400ms",
      currentLatency: "135ms",
      healthy: true,
    },
    whoHasAccess: [
      { plan: "Free", workspaces: 0, access: false },
      { plan: "Pro", workspaces: 210, access: true },
      { plan: "Business", workspaces: 220, access: true },
      { plan: "Enterprise", workspaces: 100, access: true },
    ],
  },
  {
    id: "feat-consulting-playbooks",
    name: "Interactive SOP & Consulting Playbooks",
    productId: "office-sahayogi",
    productName: "Office Sahayogi",
    description: "Curated standard operating procedures, organizational design blueprints and delegation frameworks",
    availability: ["Business", "Enterprise"],
    adoptionRate: 64.2,
    activeWorkspaces: 380,
    monthlyUsage: "95,000 runs",
    flagId: "flag-consulting-playbooks",
    rolloutPercentage: 80,
    status: "Beta",
    telemetryGate: {
      errorRateThreshold: "< 0.1%",
      currentErrorRate: "0.04%",
      latencyThreshold: "< 500ms",
      currentLatency: "180ms",
      healthy: true,
    },
    whoHasAccess: [
      { plan: "Free", workspaces: 0, access: false },
      { plan: "Pro", workspaces: 0, access: false },
      { plan: "Business", workspaces: 240, access: true },
      { plan: "Enterprise", workspaces: 140, access: true },
    ],
  },

  // Studio Sahayogi
  {
    id: "feat-multi-agent",
    name: "Multi-Agent Smart Routing",
    productId: "studio-sahayogi",
    productName: "Studio Sahayogi",
    description: "Skill-based automatic agent handoffs with intent classification and fallback queues",
    availability: ["Business", "Enterprise"],
    adoptionRate: 38.6,
    activeWorkspaces: 198,
    monthlyUsage: "310,000 events",
    flagId: "flag-multi-agent-routing",
    rolloutPercentage: 30,
    status: "Canary",
    telemetryGate: {
      errorRateThreshold: "< 1.0%",
      currentErrorRate: "0.42%",
      latencyThreshold: "< 450ms",
      currentLatency: "288ms",
      healthy: true,
    },
    whoHasAccess: [
      { plan: "Free", workspaces: 0, access: false },
      { plan: "Pro", workspaces: 0, access: false },
      { plan: "Business", workspaces: 130, access: true },
      { plan: "Enterprise", workspaces: 68, access: true },
    ],
  },
  {
    id: "feat-custom-webhooks",
    name: "Real-Time Custom Webhooks",
    productId: "studio-sahayogi",
    productName: "Studio Sahayogi",
    description: "Configurable HMAC-SHA256 authenticated webhook streams with exponential retry backoff",
    availability: ["Business", "Enterprise"],
    adoptionRate: 68.3,
    activeWorkspaces: 362,
    monthlyUsage: "2,100,000 deliveries",
    flagId: "flag-webhooks",
    rolloutPercentage: 100,
    status: "GA",
    telemetryGate: {
      errorRateThreshold: "< 0.5%",
      currentErrorRate: "0.08%",
      latencyThreshold: "< 250ms",
      currentLatency: "112ms",
      healthy: true,
    },
    whoHasAccess: [
      { plan: "Free", workspaces: 0, access: false },
      { plan: "Pro", workspaces: 0, access: false },
      { plan: "Business", workspaces: 242, access: true },
      { plan: "Enterprise", workspaces: 120, access: true },
    ],
  },
];

export const mockFeatureFlags = [
  {
    id: "flag-subscription-hub",
    name: "sahayogi_one_license_hub",
    featureName: "Unified Subscription & License Hub",
    productId: "sahayogi-one",
    target: "All Commercial & Free Workspaces",
    environment: "Production",
    rolloutPercentage: 100,
    status: "GA",
    owner: "Core Identity & Entitlements",
    cohort: "Global Workspaces",
    schedule: { start: "2026-08-01", review: "2026-09-01" },
    telemetryGate: {
      rule: "Plan lookup latency < 150ms",
      currentValues: "Error: 0.01%, P99: 48ms",
      status: "Passed",
    },
    killSwitchArmed: true,
  },
  {
    id: "flag-ai-assistant-v2",
    name: "ai_assistant_v2_rollout",
    featureName: "AI Assistant V2",
    productId: "chat-sahayogi",
    target: "Pro, Business & Enterprise Plans",
    environment: "Production",
    rolloutPercentage: 65,
    status: "Active",
    owner: "Product & AI Platform Team",
    cohort: "Beta Workspaces + 50% Random Sampling",
    schedule: { start: "2026-09-01", review: "2026-09-30" },
    telemetryGate: {
      rule: "Error Rate < 0.5% & P99 Latency < 600ms",
      currentValues: "Error: 0.18%, P99: 412ms",
      status: "Passed",
    },
    killSwitchArmed: true,
  },
  {
    id: "flag-employee-portal",
    name: "my_sahayogi_self_service",
    featureName: "Employee Self-Service & Tasks",
    productId: "my-sahayogi",
    target: "Pro & Business Workspaces",
    environment: "Production",
    rolloutPercentage: 80,
    status: "Active",
    owner: "Workplace Experience Team",
    cohort: "Active Employee Workspaces",
    schedule: { start: "2026-09-05", review: "2026-10-01" },
    telemetryGate: {
      rule: "Attendance sync failure < 0.2%",
      currentValues: "Error: 0.06%, P99: 128ms",
      status: "Passed",
    },
    killSwitchArmed: true,
  },
  {
    id: "flag-gst-reconciliation",
    name: "tax_gst_reconciliation_v2",
    featureName: "Automated 2B GST Reconciliation",
    productId: "tax-sahayogi",
    target: "Pro, Business & Enterprise Plans",
    environment: "Production",
    rolloutPercentage: 90,
    status: "Active",
    owner: "Tax & Compliance Engineering",
    cohort: "Phase 2 Production Workspaces",
    schedule: { start: "2026-09-10", review: "2026-09-28" },
    telemetryGate: {
      rule: "Reconciliation discrepancy flag rate > 99.5%",
      currentValues: "Accuracy: 99.8%, P99: 410ms",
      status: "Passed",
    },
    killSwitchArmed: true,
  },
  {
    id: "flag-boss-gl",
    name: "boss_general_ledger_core",
    featureName: "Enterprise Double-Entry Ledger",
    productId: "boss",
    target: "Accounting & ERP Workspaces",
    environment: "Production",
    rolloutPercentage: 100,
    status: "GA",
    owner: "BoSS Financial Core Team",
    cohort: "General Availability",
    schedule: { start: "2026-07-15", review: "2026-08-15" },
    telemetryGate: {
      rule: "Balance sheet mathematical zero-variance",
      currentValues: "Zero Variance Verified",
      status: "Passed",
    },
    killSwitchArmed: true,
  },
  {
    id: "flag-tally-sync",
    name: "tally_prime_direct_sync",
    featureName: "Tally & BUSY Direct Cloud Sync",
    productId: "boss",
    target: "Tally Connector Users",
    environment: "Production",
    rolloutPercentage: 50,
    status: "Paused",
    owner: "Fintech Integrations Team",
    cohort: "Pilot Accounting Workspaces",
    schedule: { start: "2026-08-20", review: "2026-09-24" },
    telemetryGate: {
      rule: "Error Rate < 0.5% & Sync timeout < 2s",
      currentValues: "Error: 1.24% (Breach!), Timeout: 3.4s",
      status: "Tripped",
    },
    killSwitchArmed: true,
  },
  {
    id: "flag-office-diagnostic",
    name: "office_sme_diagnostic_engine",
    featureName: "SME Operational Health Diagnostic",
    productId: "office-sahayogi",
    target: "SME Consulting Workspaces",
    environment: "Production",
    rolloutPercentage: 100,
    status: "GA",
    owner: "Office Sahayogi Practice Lead",
    cohort: "General Availability",
    schedule: { start: "2026-06-10", review: "2026-07-20" },
    telemetryGate: {
      rule: "Diagnostic inference accuracy > 98%",
      currentValues: "99.4% Accuracy Verified",
      status: "Passed",
    },
    killSwitchArmed: true,
  },
  {
    id: "flag-llm-router",
    name: "sahayogi_ai_cognitive_router",
    featureName: "Cognitive Multi-Model LLM Router",
    productId: "sahayogi-ai",
    target: "High-Volume AI Consumers",
    environment: "Production",
    rolloutPercentage: 75,
    status: "Active",
    owner: "Sahayogi AI Research & Platform",
    cohort: "Cohort Alpha + 75% Traffic",
    schedule: { start: "2026-09-08", review: "2026-09-30" },
    telemetryGate: {
      rule: "Token latency < 700ms & Cost saving > 20%",
      currentValues: "Latency: 345ms, Savings: +24.6%",
      status: "Passed",
    },
    killSwitchArmed: true,
  },
  {
    id: "flag-multi-agent-routing",
    name: "multi_agent_smart_routing",
    featureName: "Multi-Agent Smart Routing",
    productId: "studio-sahayogi",
    target: "Business & Enterprise Workspaces",
    environment: "Production",
    rolloutPercentage: 30,
    status: "Canary",
    owner: "Studio Core Team",
    cohort: "Canary Workspaces Group A",
    schedule: { start: "2026-09-15", review: "2026-10-05" },
    telemetryGate: {
      rule: "Error Rate < 1.0% & Routing Handoff P95 < 450ms",
      currentValues: "Error: 0.42%, P95: 288ms",
      status: "Passed",
    },
    killSwitchArmed: true,
  },
  {
    id: "flag-waba-v19",
    name: "meta_graph_api_v19",
    featureName: "WhatsApp Cloud API v19",
    productId: "chat-sahayogi",
    target: "Global All Workspaces",
    environment: "Production",
    rolloutPercentage: 100,
    status: "GA",
    owner: "Messaging Infra Team",
    cohort: "All Active Workspaces",
    schedule: { start: "2026-08-10", review: "2026-09-10" },
    telemetryGate: {
      rule: "Webhook delivery failure < 0.2%",
      currentValues: "Failure: 0.04%",
      status: "Passed",
    },
    killSwitchArmed: true,
  },
  {
    id: "flag-bulk-export",
    name: "encrypted_bulk_export",
    featureName: "Encrypted Bulk Data Export",
    productId: "sahayogi-cloud",
    target: "Business & Enterprise Plans",
    environment: "Production",
    rolloutPercentage: 100,
    status: "GA",
    owner: "Security & Governance Team",
    cohort: "General Availability",
    schedule: { start: "2026-07-01", review: "2026-08-01" },
    telemetryGate: {
      rule: "Decryption verify checksum = 100%",
      currentValues: "100% verified",
      status: "Passed",
    },
    killSwitchArmed: true,
  },
];

export const mockPlanEntitlements = [
  {
    feature: "Sahayogi One Unified Portal",
    type: "Boolean",
    free: true,
    pro: true,
    business: true,
    enterprise: true,
    detail: "Central user cockpit tracking all product plans, entitlements & expiry dates",
  },
  {
    feature: "AI Assistant (Chat with Sahayogi)",
    type: "Boolean / Tiered",
    free: false,
    pro: true,
    business: true,
    enterprise: true,
    detail: "Pro: 50k tokens | Business: 500k tokens | Enterprise: Unlimited with BYOK",
  },
  {
    feature: "My Sahayogi Employee Seats",
    type: "Quantity",
    free: "2 Members",
    pro: "15 Members",
    business: "50 Members",
    enterprise: "Custom (Unlimited)",
    detail: "Self-service HR attendance, tasks and personal assistant",
  },
  {
    feature: "Tax Sahayogi e-Invoices & GST",
    type: "Consumption",
    free: "10 / mo",
    pro: "500 / mo",
    business: "5,000 / mo",
    enterprise: "Unlimited Custom",
    detail: "Direct NIC IRP generation with digital signatures",
  },
  {
    feature: "BoSS ERP Accounting & Sync",
    type: "Integration",
    free: false,
    pro: true,
    business: true,
    enterprise: true,
    detail: "TallyPrime & BUSY direct bridge ledger connector",
  },
  {
    feature: "Sahayogi AI Model Gateway",
    type: "Consumption",
    free: "50,000 tokens",
    pro: "2M tokens",
    business: "10M tokens",
    enterprise: "Dedicated Cluster",
    detail: "Dynamic multi-model router with RAG vector search",
  },
  {
    feature: "WhatsApp Business Numbers",
    type: "Quantity",
    free: "1 WABA",
    pro: "3 WABA",
    business: "10 WABA",
    enterprise: "Custom (Unlimited)",
    detail: "Metered connection limit per workspace",
  },
  {
    feature: "Encrypted Bulk Export (Cloud)",
    type: "Boolean",
    free: false,
    pro: false,
    business: true,
    enterprise: true,
    detail: "Full schema JSON/CSV automated nightly export",
  },
  {
    feature: "Sub-100ms Priority SLA",
    type: "Service Level",
    free: false,
    pro: false,
    business: false,
    enterprise: true,
    detail: "Dedicated processing queue and warm replica",
  },
];

export const mockLimitPressures = [
  {
    id: "LP-101",
    workspaceName: "Zenith Retail Solutions",
    workspaceId: "ws-zenith-09",
    plan: "Business",
    product: "Chat with Sahayogi",
    meter: "Monthly AI Tokens",
    consumed: "485,200",
    limit: "500,000",
    pressurePercentage: 97.0,
    status: "Critical (97%)",
    actionRecommended: "Suggest upgrade to Enterprise or token add-on pack",
  },
  {
    id: "LP-102",
    workspaceName: "Aarav Logistics LLP",
    workspaceId: "ws-aarav-33",
    plan: "Pro",
    product: "Chat with Sahayogi",
    meter: "WhatsApp Conversations",
    consumed: "8,920",
    limit: "10,000",
    pressurePercentage: 89.2,
    status: "Warning (89%)",
    actionRecommended: "Soft quota warning sent to workspace admin",
  },
  {
    id: "LP-103",
    workspaceName: "Nexus Health Informatics",
    workspaceId: "ws-nexus-71",
    plan: "Pro",
    product: "Sahayogi Cloud",
    meter: "Cloud Storage GB",
    consumed: "94.2 GB",
    limit: "100 GB",
    pressurePercentage: 94.2,
    status: "Critical (94%)",
    actionRecommended: "Storage limit pressure banner active in customer app",
  },
  {
    id: "LP-104",
    workspaceName: "FinScale Technologies",
    workspaceId: "ws-finscale-12",
    plan: "Business",
    product: "Tax Sahayogi",
    meter: "GST & e-Invoice API Calls",
    consumed: "4,420",
    limit: "5,000",
    pressurePercentage: 88.4,
    status: "Warning (88%)",
    actionRecommended: "Usage on track to exceed threshold in 4 days",
  },
  {
    id: "LP-105",
    workspaceName: "Global Trade Dynamics",
    workspaceId: "ws-gtd-44",
    plan: "Enterprise",
    product: "Sahayogi AI",
    meter: "LLM Cognitive Tokens",
    consumed: "9.62M",
    limit: "10.0M",
    pressurePercentage: 96.2,
    status: "Critical (96%)",
    actionRecommended: "Autoscale high-throughput token lane authorized",
  },
  {
    id: "LP-106",
    workspaceName: "Omicron Enterprises",
    workspaceId: "ws-omic-88",
    plan: "Pro",
    product: "Sahayogi One",
    meter: "Active Licensed User Seats",
    consumed: "14",
    limit: "15",
    pressurePercentage: 93.3,
    status: "Warning (93%)",
    actionRecommended: "Workspace approaching seat limit; prompt admin",
  },
  {
    id: "LP-107",
    workspaceName: "Vanguard Retail Corp",
    workspaceId: "ws-vang-22",
    plan: "Business",
    product: "BoSS",
    meter: "Concurrent Ledger Sync Sessions",
    consumed: "43",
    limit: "50",
    pressurePercentage: 86.0,
    status: "Warning (86%)",
    actionRecommended: "Sync queue healthy; soft advisory notified",
  },
  {
    id: "LP-108",
    workspaceName: "Kavya Consulting Group",
    workspaceId: "ws-kavya-65",
    plan: "Pro",
    product: "My Sahayogi",
    meter: "Self-Service Document Vault",
    consumed: "21.5 GB",
    limit: "25 GB",
    pressurePercentage: 86.0,
    status: "Warning (86%)",
    actionRecommended: "Encourage document archival or storage pack expansion",
  },
];

export const mockAdoptionTrend = [
  { month: "Apr", overall: 58, aiAssistant: 42, whatsappCloud: 72, multiAgent: 18 },
  { month: "May", overall: 64, aiAssistant: 51, whatsappCloud: 78, multiAgent: 22 },
  { month: "Jun", overall: 69, aiAssistant: 59, whatsappCloud: 84, multiAgent: 27 },
  { month: "Jul", overall: 73, aiAssistant: 66, whatsappCloud: 88, multiAgent: 31 },
  { month: "Aug", overall: 76, aiAssistant: 71, whatsappCloud: 90, multiAgent: 35 },
  { month: "Sep", overall: 78.4, aiAssistant: 74.5, whatsappCloud: 92.4, multiAgent: 38.6 },
];

export const mockReleases = [
  {
    id: "rel-01",
    productName: "Sahayogi One",
    version: "v1.4.2",
    buildNumber: "build-1042",
    environment: "Production",
    cohort: "100% General Availability",
    deployedAt: "2026-09-22 10:15 IST",
    initiator: "pipeline-ci/cd-prod",
    errorRateBefore: "0.02%",
    errorRateAfter: "0.01%",
    status: "Active",
    rollbackAvailable: true,
  },
  {
    id: "rel-02",
    productName: "Chat with Sahayogi",
    version: "v3.1.2",
    buildNumber: "build-9824",
    environment: "Production",
    cohort: "100% General Availability",
    deployedAt: "2026-09-18 14:30 IST",
    initiator: "pipeline-ci/cd-prod",
    errorRateBefore: "0.12%",
    errorRateAfter: "0.18%",
    status: "Active",
    rollbackAvailable: true,
  },
  {
    id: "rel-03",
    productName: "My Sahayogi",
    version: "v2.1.0",
    buildNumber: "build-3310",
    environment: "Production",
    cohort: "100% General Availability",
    deployedAt: "2026-09-17 12:00 IST",
    initiator: "pipeline-ci/cd-prod",
    errorRateBefore: "0.05%",
    errorRateAfter: "0.04%",
    status: "Active",
    rollbackAvailable: true,
  },
  {
    id: "rel-04",
    productName: "Tax Sahayogi",
    version: "v1.8.5",
    buildNumber: "build-5419",
    environment: "Production",
    cohort: "100% General Availability",
    deployedAt: "2026-09-19 16:20 IST",
    initiator: "pipeline-ci/cd-prod",
    errorRateBefore: "0.08%",
    errorRateAfter: "0.06%",
    status: "Active",
    rollbackAvailable: true,
  },
  {
    id: "rel-09",
    productName: "Office Sahayogi",
    version: "v2.3.0",
    buildNumber: "build-4912",
    environment: "Production",
    cohort: "100% General Availability",
    deployedAt: "2026-09-22 14:10 IST",
    initiator: "aditya.sharma (Release Eng)",
    errorRateBefore: "0.03%",
    errorRateAfter: "0.02%",
    status: "Active",
    rollbackAvailable: true,
  },
  {
    id: "rel-05",
    productName: "BoSS",
    version: "v4.0.2",
    buildNumber: "build-8730",
    environment: "Production",
    cohort: "100% General Availability",
    deployedAt: "2026-09-21 16:45 IST",
    initiator: "aditya.sharma (Release Eng)",
    errorRateBefore: "0.03%",
    errorRateAfter: "0.02%",
    status: "Active",
    rollbackAvailable: true,
  },
  {
    id: "rel-06",
    productName: "Investor Sahayogi",
    version: "v2.1.0",
    buildNumber: "build-7740",
    environment: "Production",
    cohort: "100% General Availability",
    deployedAt: "2026-09-20 09:40 IST",
    initiator: "pipeline-ci/cd-prod",
    errorRateBefore: "0.10%",
    errorRateAfter: "0.07%",
    status: "Active",
    rollbackAvailable: true,
  },
  {
    id: "rel-07",
    productName: "Sahayogi Cloud",
    version: "v2.8.4",
    buildNumber: "build-6521",
    environment: "Production",
    cohort: "100% General Availability",
    deployedAt: "2026-09-08 09:20 IST",
    initiator: "pipeline-ci/cd-prod",
    errorRateBefore: "0.02%",
    errorRateAfter: "0.01%",
    status: "Active",
    rollbackAvailable: true,
  },
  {
    id: "rel-08",
    productName: "Studio Sahayogi",
    version: "v1.9.0",
    buildNumber: "build-4129",
    environment: "Production",
    cohort: "30% Canary Cohort A",
    deployedAt: "2026-09-15 11:15 IST",
    initiator: "pipeline-ci/cd-prod",
    errorRateBefore: "0.08%",
    errorRateAfter: "0.07%",
    status: "Canary Testing",
    rollbackAvailable: true,
  },
];

export const mockRecentActivity = [
  {
    id: "act-1",
    type: "feature-flag",
    title: "AI Assistant V2 rollout expanded to 65%",
    description: "Automated telemetry gate passed (Error rate 0.18% < 0.5%). Rollout expanded from 50% to 65%.",
    timestamp: "45 mins ago",
    badge: "Rollout",
    badgeColor: "blue",
  },
  {
    id: "act-2",
    type: "incident",
    title: "Incident INC-910 opened: AI Gateway latency spike",
    description: "Upstream model gateway latency exceeded P99 1800ms. SRE team investigating.",
    timestamp: "28 mins ago",
    badge: "Incident",
    badgeColor: "red",
  },
  {
    id: "act-3",
    type: "limit-pressure",
    title: "Quota limit alert: Zenith Retail Solutions at 97%",
    description: "Monthly AI tokens reached 485,200 of 500,000 limit. Notification dispatched.",
    timestamp: "2 hours ago",
    badge: "Quota",
    badgeColor: "yellow",
  },
  {
    id: "act-4",
    type: "release",
    title: "BoSS v4.0.2 deployed to Production",
    description: "Tenant Zero validation test run completed with 100% pass rate on ledger sync.",
    timestamp: "Yesterday",
    badge: "Release",
    badgeColor: "green",
  },
  {
    id: "act-5",
    type: "feature-flag",
    title: "Tally & BUSY Direct Cloud Sync rollout paused",
    description: "Safety telemetry gate tripped due to desktop socket connection timeout. Rollout held at 50%.",
    timestamp: "2 days ago",
    badge: "Safety Gate",
    badgeColor: "yellow",
  },
];
